name: docker-build-and-push-ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${GITHUB_SHA::7}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Get short SHA
        id: slug
        run: echo "GIT_SHORT_SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/abstractumbra/honeypot:${{ steps.slug.outputs.GIT_SHORT_SHA7 }}
            ghcr.io/abstractumbra/honeypot:latest
          labels: ${{ steps.meta.outputs.labels }}
